name: Feat

on:
  workflow_dispatch:
  push:
    branches:
      - main  

permissions:
  contents: write

jobs:
  branch:
    name: Feat
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'feat:') }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: validate step
        id: validacao
        run: |
          git fetch
          git checkout main
          currentstep=$(cat .github/CONFIG/step.txt)
          echo "::set-output name=currentstep::$currentstep"   

      - name: Create an issue
        if: ${{ steps.validacao.outputs.currentstep == '1' }} 
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.ISSUE_SECRET }}
          title: Você fez um Feature!!!!
          body: |
            ## UHULLL, Você conseguiu fazer uma Feature!!

            E ai, foi facil? Bora seguir para as próximas?

            Deixa eu conferir aqui na lista, qual é agora..

            Ah, achei, agora é: **fix**

            Não se esqueça de fazer um **git pull** antes de sua proxima alteração.. :wink:

            Estou te esperando eim!!!
            
            ![hula_loop_octodex](https://octodex.github.com/images/Fintechtocat.png)

      - name: Update Step
        if: ${{ steps.validacao.outputs.currentstep == '1' }}      
        run: |
          git fetch
          git checkout main
          echo "2" > .github/CONFIG/step.txt
          git config --global user.name 'Julio Arruda'
          git config --global user.email 'julio.arruda@outlook.com'          
          git add .
          git commit -m "Atualizando Step"
          git push
