name: Chore

on:
  workflow_dispatch:
  push:
    branches:
      - main  

permissions:
  contents: write

jobs:
  branch:
    name: Chore
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'chore:') }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: validate step
        id: validacao
        run: |
          git fetch
          git checkout main
          currentstep=$(cat .github/CONFIG/step.txt)
          echo "::set-output name=currentstep::$currentstep"   

      - name: Create an issue
        if: ${{ steps.validacao.outputs.currentstep == '7' }} 
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.ISSUE_SECRET }}
          title: Você fez um Chore!!!!
          body: |
            ## E não é que você conseguiu fazer um Chore?!

            E ai, oque achou desse desafio? Deu pra entender a convenção de commits?
            Espero que sim! E não deixe de usar isso em seus proximos projetos.

            Se seu time não conhecer as convenções de commit, não deixe de apresentar ao time,
            tenho certeza que isso poderá agregar muito valor ao desenvolvimento do projeto.

            Até o próximo desafio! Bons estudos!!
            
            ![hula_loop_octodex](https://octodex.github.com/images/Fintechtocat.png)

      - name: Atualizar Issue Desafio
        if: ${{ steps.validacao.outputs.currentstep == '7' }} 
        id: issueinfo 
        run: |
          issuenumber="$(cat .github/CONFIG/issue.txt | grep "id" | cut -d":" -f2)"
          nome="$(cat .github/CONFIG/issue.txt | grep "nome" | cut -d":" -f2)"
          email="$(cat .github/CONFIG/issue.txt | grep "email" | cut -d":" -f2)"
          identificado=$(uuidgen)

          echo "::set-output name=issuenumber::$issuenumber"
          echo "::set-output name=nome::$nome"
          echo "::set-output name=email::$email"
          echo "::set-output name=identificado::$identificado"

      - name: Iniciar Processo Badge
        if: ${{ steps.validacao.outputs.currentstep == '7' }}  
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ secrets.ISSUE_SECRET }}
          owner: julioarruda
          repo: arruda-events-badge
          title: '[Desafio 1] ${{ steps.issueinfo.outputs.nome }}'
          body: |
            participant:${{ steps.issueinfo.outputs.nome }}
            id:${{ steps.issueinfo.outputs.identificado }}
            event:desafio_padroes_commit            
            email:${{ steps.issueinfo.outputs.email }}